### PR TITLE
Add fundamentals data to the api.

### PR DESCRIPTION
**Pull request by jspenc72**
The robin hood api has the following endpoint: 
```
https://api.robinhood.com/fundamentals/
```

Fundamental data is extremely useful and has this form:

```json
{
 results: 
   [ { open: '22.9700',
       high: '27.0400',
       low: '22.8200',
       volume: '3361134.0000',
       average_volume: '2100192.1896',
       high_52_weeks: '352.5000',
       dividend_yield: '0.0000',
       low_52_weeks: '18.3614',
       market_cap: null,
       pe_ratio: null,
       description: '',
       instrument: 'https://api.robinhood.com/instruments/c9334c71-c95d-4da0-b6c2-13a01f306c50/'    } ] 
}
```

### CODE REVIEW

**Comment by jspenc72** [comment]
@aurbano Hey any chance you can merge this?

**Comment by jspenc72** [comment]
Hey this pull request expands the coverage of this plugin to include an additional endpoint of the robin hood api and only requires changes to a few lines of code.

Please can you review and merge this?

**Comment by aurbano** [comment]
@jspenc72 I was on holidays last week, thanks for this PR!

All looking good :+1:

**Comment by jspenc72** [comment]
Thanks!

**Comment by jspenc72** [comment]
And I appreciate your adding me to the list of contributors. 

Cheers!

**Pull request merged**
