### PR TITLE
Major improvements to api

### PR DESCRIPTION
**Pull request by jspenc72**
I recommend bumping the version to 0.4

### CODE REVIEW

**Comment by jspenc72** [comment]
@aurbano Ok so this version is ready to go. I added functionality related to watchlists, splits, historicals, and sp500 movers among various other things.

If you like what you see, then please bump version and push to npm

**Comment by aurbano** [comment]
@jspenc72 thanks for the changes and updates. Since you want to maintain two different versions of the framework it could be a good time to use the fork for actual breaking changes.

I'll rewrite my version to use promises and a more polished API and publish that as version 1. I'd rather stay with semver and not jump to 2 or any other version number.

**Comment by jspenc72** [comment]
Sounds great!

**Comment by jspenc72** [comment]
Looking forward to seeing what you've got for v1

**Pull request merged**
